"""add is_rejected to loans

Revision ID: 0919f5d311db
Revises: 23e0dd317f4a
Create Date: 2025-12-29 21:30:43.801671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0919f5d311db'
down_revision: Union[str, Sequence[str], None] = '23e0dd317f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('is_rejected', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['code_meli'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('loans', 'is_rejected')
    # ### end Alembic commands ###
