"""add is_loaned to loans

Revision ID: 23e0dd317f4a
Revises: a498ca1219fe
Create Date: 2025-12-29 19:05:09.202502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e0dd317f4a'
down_revision: Union[str, Sequence[str], None] = 'a498ca1219fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('is_loaned', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['code_meli'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('loans', 'is_loaned')
    # ### end Alembic commands ###
