"""add isbn to books

Revision ID: 8990f7157e34
Revises: 2cd8116d7ba6
Create Date: 2025-12-28 15:10:46.339786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8990f7157e34'
down_revision: Union[str, Sequence[str], None] = '2cd8116d7ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_disable')
    # ### end Alembic commands ###
