"""add code_meli to user

Revision ID: a498ca1219fe
Revises: 8990f7157e34
Create Date: 2025-12-28 16:47:10.103948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a498ca1219fe'
down_revision: Union[str, Sequence[str], None] = '8990f7157e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code_meli', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['code_meli'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'code_meli')
    # ### end Alembic commands ###
